app/models/bill.py
from app.extensions import db


class Bill(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    service = db.Column(db.String(1500))
    period = db.Column(db.String(150))
    price = db.Column(db.Numeric(precision=2))

    def __repr__(self):
        return f'<Job "{self.title}">'

app/models/job.py
from app.extensions import db


class Job(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    content = db.Column(db.String(2500))

    def __repr__(self):
        return f'<Job "{self.title}">'

app/models/study_program.py
from app.extensions import db


class Program(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    organization = db.Column(db.String(150))
    description = db.Column(db.String(2500))

    def __repr__(self):
        return f'<Study program "{self.title}">'

app/__init__.py
from flask import Flask

from config import Config
from app.extensions import db
from app.models import job
from app.models import study_program
from app.models import bill


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initializing Flask extensions
    db.init_app(app)

    with app.app_context():
        db.create_all()

    # Registering blueprints
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.tasks.bills import bp as bills_bp
    app.register_blueprint(bills_bp, url_prefix='/bills')

    from app.tasks.entertainment import bp as entertainment_bp
    app.register_blueprint(entertainment_bp, url_prefix='/entertainment')

    from app.tasks.job import bp as job_bp
    app.register_blueprint(job_bp, url_prefix='/job')

    from app.tasks.studies import bp as studies_bp
    app.register_blueprint(studies_bp, url_prefix='/studies')

    from app.tasks.weather import bp as weather_bp
    app.register_blueprint(weather_bp, url_prefix='/weather')

    return app


if __name__ == "__main__":
    create_app().run(debug=True)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


# Imports the bp blueprint object from the main blueprint
@bp.route('/')
def index():
    return render_template("index.html")

app/tasks/bills/__init__.py
from flask import Blueprint

bp = Blueprint('bills', __name__)

from app.tasks.bills import routes

app/tasks/bills/routes.py
from flask import render_template, request, redirect, url_for

from app import db
from app.models.bill import Bill
from app.tasks.bills import bp


@bp.route('/')
def index():
    bills = Bill.query.all()
    return render_template('bills/index.html', bills=bills)


@bp.route('/new/', methods=('GET', 'POST'))
def new():
    if request.method == 'POST':
        new_bill = Bill(service=request.form['service'],
                        period=request.form['period'],
                        price=request.form['price'])
        db.session.add(new_bill)
        db.session.commit()
        return redirect(url_for('bills.index'))
    return render_template('bills/new-bill.html')


@bp.route('/edit/<id>', methods=['GET', 'POST'])
def get_bill_by_id_for_edit(id):
    bill = Bill.query.filter_by(id=id).first()
    return render_template('bills/edit-bill.html', bill=bill)


@bp.route('/update/<id>', methods=['GET', 'POST'])
def update(id):
    bill = Bill.query.filter_by(id=id).first()
    bill.service = request.form["service"]
    bill.period = request.form["period"]
    bill.price = request.form["price"]
    db.session.commit()
    return index()


@bp.route('/delete/<id>', methods=['GET', 'POST'])
def delete(id):
    bill = Bill.query.filter_by(id=id).first()
    db.session.delete(bill)
    db.session.commit()
    return index()

app/tasks/entertainment/__init__.py
from flask import Blueprint

bp = Blueprint('entertainment', __name__)

from app.tasks.entertainment import routes

app/tasks/entertainment/routes.py
from flask import render_template
from app.tasks.entertainment import bp


@bp.route('/')
def index():
    return render_template('entertainment/index.html')


@bp.route('/cinema/')
def categories():
    return render_template('entertainment/cinema.html')

app/tasks/job/__init__.py
from flask import Blueprint

bp = Blueprint('job', __name__)

from app.tasks.job import routes

app/tasks/job/routes.py
from flask import render_template, request, redirect, url_for

from app import db
from app.models.job import Job
from app.tasks.job import bp


@bp.route('/')
def index():
    jobs = Job.query.all()
    return render_template('job/index.html', jobs=jobs)


@bp.route('/new/', methods=('GET', 'POST'))
def new():
    if request.method == 'POST':
        new_job = Job(title=request.form['title'],
                      content=request.form['content'])
        db.session.add(new_job)
        db.session.commit()
        return redirect(url_for('job.index'))
    return render_template('job/new-job.html')


@bp.route('/edit/<id>', methods=['GET', 'POST'])
def get_job_by_id_for_edit(id):
    job = Job.query.filter_by(id=id).first()
    return render_template('job/edit-job.html', job=job)


@bp.route('/update/<id>', methods=['GET', 'POST'])
def update(id):
    job = Job.query.filter_by(id=id).first()
    job.title = request.form["title"]
    job.content = request.form["content"]
    db.session.commit()
    return index()


@bp.route('/delete/<id>', methods=['GET', 'POST'])
def delete(id):
    job = Job.query.filter_by(id=id).first()
    db.session.delete(job)
    db.session.commit()
    return index()

app/tasks/studies/__init__.py
from flask import Blueprint

bp = Blueprint('studies', __name__)

from app.tasks.studies import routes

app/tasks/studies/routes.py
from flask import render_template, request, redirect, url_for

from app import db
from app.models.study_program import Program
from app.tasks.studies import bp


@bp.route('/')
def index():
    programs = Program.query.all()
    return render_template('studies/index.html', programs=programs)


@bp.route('/new/', methods=('GET', 'POST'))
def new():
    if request.method == 'POST':
        new_program = Program(title=request.form['title'],
                              organization=request.form['organization'],
                              description=request.form['description'])
        db.session.add(new_program)
        db.session.commit()
        return redirect(url_for('studies.index'))
    return render_template('studies/new_program.html')


@bp.route('/edit/<id>', methods=['GET', 'POST'])
def get_program_by_id_for_edit(id):
    program = Program.query.filter_by(id=id).first()
    return render_template('studies/edit-program.html', program=program)


@bp.route('/update/<id>', methods=['GET', 'POST'])
def update(id):
    program = Program.query.filter_by(id=id).first()
    program.title = request.form["title"]
    program.organization = request.form["organization"]
    program.description = request.form["description"]
    db.session.commit()
    return index()


@bp.route('/delete/<id>', methods=['GET', 'POST'])
def delete(id):
    program = Program.query.filter_by(id=id).first()
    db.session.delete(program)
    db.session.commit()
    return index()

app/tasks/weather/__init__.py
from flask import Blueprint

bp = Blueprint('weather', __name__)

from app.tasks.weather import routes

app/tasks/weather/routes.py
from flask import render_template
from app.tasks.weather import bp


@bp.route('/')
def index():
    return render_template('weather/index.html')


@bp.route('/beach/')
def categories():
    return render_template('weather/beach.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
</head>
<body>
<nav>
    <a href="{{ url_for('main.index') }}">Tasks</a>
    <a href="{{ url_for('job.index') }}">Job Search</a>
    <a href="{{ url_for('studies.index') }}">Studies</a>
    <a href="{{ url_for('bills.index') }}">Payment of Bills</a>
    <a href="{{ url_for('entertainment.index') }}">Entertainment</a>
    <a href="{{ url_for('weather.index') }}">Waiting for the Right Weather</a>

</nav>
<hr>
<div class="content">
    {% block content %} {% endblock %}
</div>
</body>
</html>

app/templates/bills/edit-bill.html
{% extends 'base.html' %}
{% block content %}
<form action="/bills/update/{{bill.id}}" method="post">
    <h1 class="mt-4 mb-4">Edit Job</h1>
    <form method="post">
        <div class="form-control form-control-lg">
            <label for="service">Service: </label>
            <input class="form-control" type="text" id="service" name="service" placeholder="{{bill.service}}">
        </div>
        <div class="form-control form-control-lg">
            <label for="period">Period: </label>
            <input class="form-control" type="text" id="period" name="period"
                   placeholder="{{bill.period}}">
        </div>
        <div class="form-control form-control-lg">
            <label for="price">Price: </label>
            <input class="form-control" type="text" id="price" name="price"
                   placeholder="{{bill.price}}">
        </div>
        <button name="bill" type="submit">Update Bill</button>
    </form>
    {% endblock %}

app/templates/bills/index.html
{% extends 'base.html' %}

{% block content %}
<span class="title"><h1>{% block title %} Manage Bills {% endblock %}</h1></span>
<div class="content">
    <h2><a href="/bills/new">Add New Bill</a></h2>
    <br>
    <hr>
</div>
<div class="content">
    <h2>Saved Bills</h2>
    {% for bill in bills %}
    <div>
        <p>
            <b>
                <a>
                    {{ bill.service }}
                </a>
            </b>
        </p>
        <div class="content">
            <p>{{ bill.period }}</p>
        </div>
        <div class="content">
            <p>{{ bill.price }}</p>
        </div>
        <form action="/bills/edit/{{bill.id}}" method=post>
            <input type="hidden" name="id" value="">
            <input type="submit" value="Edit" class="button"/>
        </form>
        <form action="/bills/delete/{{bill.id}}" method=post>
            <input type="hidden" name="id" value="">
            <input type="submit" value="Delete" class="button"/>
        </form>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/bills/mobile_bill.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Mobile Bills {% endblock %}</h1></span>
    <div class="content">
        <h2>July</h2>
    </div>
{% endblock %}

app/templates/bills/new-bill.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    <h1 class="mt-4 mb-4">Add New Bill</h1>
    <form method="post">
        <div class="form-control form-control-lg">
            <label for="service">Service: </label>
            <input class="form-control" type="text" id="service" name="service">
        </div>
        <div class="form-control form-control-lg">
            <label for="period">Period: </label>
            <input class="form-control" type="text" id="period" name="period">
        </div>
        <div class="form-control form-control-lg">
            <label for="price">Price: </label>
            <input class="form-control" type="text" id="price" name="price">
        </div>
        <button name="bill" type="submit">Add Bill</button>
    </form>
    {% endblock %}

app/templates/entertainment/cinema.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Cinema: Artis - La nuit du 12 {% endblock %}</h1></span>
    <div class="content">
        <h2>Thursday</h2>
    </div>
{% endblock %}

app/templates/entertainment/index.html
{% extends 'base.html' %}

{% block content %}
<span class="title"><h1>{% block title %} Places to Visit {% endblock %}</h1></span>
<div class="content">
    <h2><a href="/entertainment/cinema">Cinema: Artis - La nuit du 12</a></h2>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<span class="title"><h1>{% block title %} The Main Tasks of Your Lifetime {% endblock %}</h1></span>
<div class="content">
    <a href="{{ url_for('job.index') }}"><h3>Job Search</h3>
        <img src="{{ url_for('static', filename='images/job.png') }}"/>

        <a href="{{ url_for('studies.index') }}"><h3>Studies</h3>
            <img src="{{ url_for('static', filename='images/study.png') }}"/>

            <a href="{{ url_for('bills.index') }}"><h3>Payment of Bills</h3>
                <img src="{{ url_for('static', filename='images/bills.png') }}"/>

                <a href="{{ url_for('entertainment.index') }}"><h3>Entertainment</h3>
                    <img src="{{ url_for('static', filename='images/entertainment.png') }}"/>

                    <a href="{{ url_for('weather.index') }}"><h3>Waiting for the Right Weather</h3>
                        <img src="{{ url_for('static', filename='images/weather.png') }}"/>
</div>
{% endblock %}

app/templates/job/edit-job.html
{% extends 'base.html' %}
{% block content %}
<form  action="/job/update/{{job.id}}" method="post">
    <h1 class="mt-4 mb-4">Edit Job</h1>
    <form method="post">
        <div class="form-control form-control-lg">
            <label for="title">Job Title: </label>
            <input class="form-control" type="text" id="title" name="title" placeholder="{{job.title}}">
        </div>
        <div class="form-control form-control-lg">
            <label for="content">Content: </label>
            <textarea id="content" name="content" rows="5" cols="133" placeholder="{{job.content}}"></textarea>
        </div>
        <button name="job" type="submit">Update Job</button>
    </form>
    {% endblock %}

app/templates/job/index.html
{% extends 'base.html' %}

{% block content %}
<span class="title"><h1>{% block title %} Job Applications {% endblock %}</h1></span>
<div class="content">
    <h2><a href="/job/new">Add New Job</a></h2>
    <br>
    <hr>
</div>
<div class="content">
    <h2>Saved Jobs</h2>
    {% for job in jobs %}
    <div>
        <p>
            <b>
                <a>
                    {{ job.title }}
                </a>
            </b>
        </p>
        <div class="content">
            <p>{{ job.content }}</p>
        </div>
        <form action="/job/edit/{{job.id}}" method=post>
            <input type="hidden" name="id" value="">
            <input type="submit" value="Edit" class="button"/>
        </form>
        <form action="/job/delete/{{job.id}}" method=post>
            <input type="hidden" name="id" value="">
            <input type="submit" value="Delete" class="button"/>
        </form>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/job/java_intern.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Java Development Internship {% endblock %}</h1></span>
    <div class="content">
        <h2>Information</h2>
    </div>
{% endblock %}

app/templates/job/javaintern.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Java Development Internship {% endblock %}</h1></span>
    <div class="content">
        <h2>Information</h2>
    </div>
{% endblock %}

app/templates/job/new-job.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    <h1 class="mt-4 mb-4">Add New Job</h1>
    <form action="#" method="post">
        <div class="form-control form-control-lg">
            <label for="title">Job Title: </label>
            <input class="form-control" type="text" id="title" name="title">
        </div>
        <div class="form-control form-control-lg">
            <label for="content">Content: </label>
            <textarea id="content" name="content" rows="5" cols="133"></textarea>
        </div>
        <button name="job" type="submit">Add Job</button>
    </form>
    {% endblock %}

app/templates/studies/edit-program.html
{% extends 'base.html' %}
{% block content %}
<form action="/studies/update/{{program.id}}" method="post">
    <h1 class="mt-4 mb-4">Edit Job</h1>
    <form method="post">
        <div class="form-control form-control-lg">
            <label for="title">Job Title: </label>
            <input class="form-control" type="text" id="title" name="title" placeholder="{{program.organization}}">
        </div>
        <div class="form-control form-control-lg">
            <label for="organization">Organization: </label>
            <input class="form-control" type="text" id="organization" name="organization"
                   placeholder="{{program.organization}}">
        </div>
        <div class="form-control form-control-lg">
            <label for="description">Description: </label>
            <input class="form-control" type="text" id="description" name="description"
                   placeholder="{{program.description}}">
        </div>
        <button name="program" type="submit">Update Program</button>
    </form>
    {% endblock %}

app/templates/studies/index.html
{% extends 'base.html' %}

{% block content %}
<span class="title"><h1>{% block title %} Study Programs {% endblock %}</h1></span>
<div class="content">
    <h2><a href="/studies/new">Add New Program</a></h2>
    <br>
    <hr>
</div>
<div class="content">
    <h2>Saved Programs</h2>
    {% for program in programs %}
    <div>
        <p>
            <b>
                <a>
                    {{ program.title }}
                </a>
            </b>
        </p>
        <div class="content">
            <p>{{ program.organization }}</p>
        </div>
                <div class="content">
            <p>{{ program.description }}</p>
        </div>
        <form action="/studies/edit/{{program.id}}" method=post>
            <input type="hidden" name="id" value="">
            <input type="submit" value="Edit" class="button"/>
        </form>
        <form action="/studies/delete/{{program.id}}" method=post>
            <input type="hidden" name="id" value="">
            <input type="submit" value="Delete" class="button"/>
        </form>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/studies/new_program.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    <h1 class="mt-4 mb-4">Add New Program</h1>
    <form method="post">
        <div class="form-control form-control-lg">
            <label for="title">Program Title: </label>
            <input class="form-control" type="text" id="title" name="title">
        </div>
              <div class="form-control form-control-lg">
            <label for="organization">Organization: </label>
            <input class="form-control" type="text" id="organization" name="organization">
        </div>
              <div class="form-control form-control-lg">
            <label for="description">Description: </label>
            <input class="form-control" type="text" id="description" name="description">
        </div>
        <button name="program" type="submit">Add Program</button>
    </form>
    {% endblock %}

app/templates/weather/beach.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Beach {% endblock %}</h1></span>
    <div class="content">
        <h2>Pärnu</h2>
    </div>
{% endblock %}

app/templates/weather/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Weather {% endblock %}</h1></span>
    <div class="content">
        <h2><a href="/weather/beach">Beach</a></h2>
    </div>
{% endblock %}